# Generated by Django 2.2 on 2019-05-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='update_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_content', models.BooleanField()),
                ('is_debug', models.BooleanField()),
                ('detail', models.CharField(max_length=200)),
            ],
        ),
    ]
