# Generated by Django 2.2 on 2019-05-31 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_merge_20190531_0049'),
        ('Download', '0006_auto_20190531_1636'),
        ('System', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='download_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('filename', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Download.Download_file')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='User.User')),
            ],
        ),
    ]
