# Generated by Django 2.2.2 on 2019-08-06 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_auto_20190806_1019'),
        ('System', '0003_ip_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='no2name_querylog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('query', models.CharField(max_length=50)),
                ('query_type', models.CharField(choices=[('cname', 'chinese_name'), ('ename', 'english_name'), ('dpt', 'department'), ('gender', 'gender'), ('no', 'student_no')], max_length=30)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='User.User')),
            ],
        ),
    ]
