pipeline:

  build:
    image: docker:18.09
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=tcp://docker:2375
    commands:
      - sleep 15
      - cat /etc/resolv.conf
      - docker ps
      - docker build -t mainpage .
  
  # start the container using a detached (non-blocking)
  # step. Bonus we can see our container logs in the
  # build output.
  run:
    image: docker:18.09-dind
    detach: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=tcp://docker:2375
    commands:
      - docker run -itd -p 8005:80 mainpage

  # this container just runs a docker ps to verify
  # our container is running. Just for demo purposes,
  # not really needed.
  check_running:
    image: docker:18.09-dind
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=tcp://docker:2375
    commands:
      - sleep 5
      - docker ps

  # curl the container to test it is up and running.
  # notice that we use `docker:8000` since the container
  # is running in the docker service container.
  test:
    image: golang # because I know it has curl installed
    commands:
      - curl -v http://docker:8005

services:
  docker:
    image: docker:18.09-dind
    privileged: true
    DOCKER_DRIVER: overlay2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    