pipeline:

  build:
    image: docker:18.09-dind
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      # - DOCKER_HOST=tcp://docker:2375
    commands:
      - sleep 5
      - docker ps
      - sed -i 's/DEBUG = FALSE/DEBUG = TRUE/' Report/settings.py
      - docker build -t mainpage .
  
  # start the container using a detached (non-blocking)
  # step. Bonus we can see our container logs in the
  # build output.
  run:
    image: docker:18.09-dind
    detach: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker rm -f mainpage || true
      - docker run -itd -p 8005:80 --name mainpage mainpage

  # this container just runs a docker ps to verify
  # our container is running. Just for demo purposes,
  # not really needed.
  check_running:
    image: docker:18.09-dind
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - sleep 5
      - docker ps

    