image: docker:19.03.0
services:
  - docker:19.03.0-dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

before_script:
  - docker info

cache:
  paths:
  - ~/.cache/pip/

test:
  stage: test
  script:
    - apk --no-cache add --virtual build-dependencies build-base py-mysqldb gcc libc-dev libffi-dev mariadb-dev python3-dev
    - pip3 install -r requirements.txt
    - pip3 install pymysql
    - python3 manage.py test

deploy-build:
  stage: deploy
  variables:
    GIT_STRATEGY: fetch
  script:
    - docker build -t test-build .

deploy:
  stage: deploy
  script:
    - docker rm -f test-deploy || true
    - docker run -d -p 0.0.0.0:8000:80/tcp --name test-deploy test-build
