image: docker:19.03.0
services:
  - docker:19.03.0-dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

before_script:
  - docker info

test:
  stage: test
  script:
    - apk --no-cache add --virtual build-dependencies build-base py-mysqldb gcc libc-dev libffi-dev mariadb-dev python3-dev
    - pip3 install -r requirements.txt
    - pip3 install pymysql
    - python3 manage.py test

update-static:
  stage: deploy
  only:
    refs:
      - front-end
  script:
    - docker exec mainpage bash git pull
    
deploy-build:
  stage: deploy
  only:
    refs:
      - master
  variables:
    GIT_STRATEGY: fetch
  script:
    - docker build -t mainpage .

deploy:
  stage: deploy
  only:
    refs:
      - master
  script:
    - docker rm -f mainpage || true
    - docker run -itd -p 0.0.0.0:8000:80/tcp --name mainpage mainpage
