image: docker:19.03.0
services:
  - docker:19.03.0-dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

before_script:
  - docker info

cache:
  paths:
  - ~/.cache/pip/

test:
  image: python:3.7
  script:
    # - apt-get update && apt-get install -y python-apt unattended-upgrades libcairo2-dev
    - pip3 install -r requirements.txt
    - python3 manage.py test

deploy-build:
  variables:
    GIT_STRATEGY: fetch
  script:
    - docker build -t test-build .

deploy:
  script:
    - docker rm -f test-deploy || true
    - docker run -d -p 0.0.0.0:8000:8000/tcp --name test-deploy test-build
