# Generated by Django 2.2 on 2019-05-31 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Download', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download_file',
            name='file',
            field=models.FileField(upload_to='upload/Download Files/'),
        ),
    ]
