# Generated by Django 2.2 on 2019-05-31 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Download', '0002_auto_20190531_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download_file',
            name='file',
            field=models.FileField(upload_to='upload/Download Files'),
        ),
    ]
