# Generated by Django 2.2 on 2019-05-31 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Download', '0003_auto_20190531_0152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='download_file',
            old_name='Download_counter',
            new_name='download_counter',
        ),
    ]
