# Generated by Django 2.2 on 2019-05-31 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_auto_20190530_0821'),
        ('User', '0006_auto_20190530_1620'),
    ]

    operations = [
    ]
